# main.py
from utils import (
    init_kokoro,
    synthesize_text,
    play_audio,
    save_audio,
    generate_and_save_podcast
)

def main():
    # 1. 初始化 Kokoro 对象
    kokoro = init_kokoro(
        model_path="kokoro-v0_19.int8.onnx",
        voices_path="voices-v1.0.bin"
    )

    # 2. 合成一段文本
    text = "Hello. This audio is generated by Kokoro!"
    samples, sample_rate = synthesize_text(kokoro, text, voice="af_sarah", speed=1.0, lang="en-us")

    # 3. 播放音频
    print("Playing audio...")
    play_audio(samples, sample_rate)

    # 4. 保存到文件
    save_audio("test_output.wav", samples, sample_rate)

    # 如果需要做类似 Podcast 的多句拼接：
    sentences = [
        {"voice": "af_sarah", "text": "Hello and welcome to the podcast! We’ve got some exciting things lined up today."},
        {"voice": "am_michael", "text": "It’s going to be an exciting episode. Stick with us!"},
        {"voice": "af_sarah", "text": "But first, we’ve got a special guest with us. Please welcome Nicole!"},
    ]
    generate_and_save_podcast(
        kokoro,
        sentences=sentences,
        output_path="podcast.wav",
        random_pause=True  # 句子间插入随机停顿
    )

if __name__ == "__main__":
    main()
